### ISSUE TITLE
zstd-safe WriteBuf for Vec?

### ISSUE THREAD

**Issue by kornelski** [gyscos/zstd-rs#128]
I'm confused by `WriteBuf` in zstd-safe. It's described as:

> Describe a resizeable bytes container like `Vec<u8>`.

but it's [not implemented for `Vec`](https://docs.rs/zstd-safe/4.1.1+zstd.1.5.0/zstd_safe/trait.WriteBuf.html#implementors).

**Comment by gyscos** [comment]
Hi! It is, but with the std feature enabled.

Looks like this was not included in the doc build, will see how to fix that.

**Comment by kornelski** [comment]
Thanks! You add a warning label for it with `#[doc(cfg(feature = "std"))]`

and enable it with:

```toml
[package.metadata.docs.rs]

# Features to pass to Cargo (default: [])
features = ["feature1", "feature2"]

# Whether to pass `--all-features` to Cargo (default: false)
all-features = true
```
