### ISSUE TITLE
Example fails to build on windows for target x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by nickelc** [gyscos/zstd-rs#49]
[Example](https://docs.rs/zstd/0.4.20+zstd.1.3.6/zstd/#example) used.
[error.txt](https://github.com/gyscos/zstd-rs/files/2493978/error.txt)

**Comment by nickelc** [comment]
I found the culprit https://github.com/rust-lang/rust/issues/47048
Sorry for the noise.

**Comment by gyscos** [comment]
No problem, glad you found the issue!
I probably should set up some windows-based CI just to be sure...

**Comment by nickelc** [comment]
This is from my `appveyor.yml` for a cmdline tool
```yaml
environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
      MINGW_PATH: "C:\\mingw-w64\\x86_64-7.2.0-posix-seh-rt_v5-rev1\\mingw64"
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
      MINGW_PATH: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1\\mingw32"
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable

install:
  - if defined MINGW_PATH set PATH=%MINGW_PATH%\bin;%PATH%
```
Build fails with 7.3 and msys2
