### ISSUE TITLE
zstdmt in the high-level API and possible zstd-sys release issue

### ISSUE THREAD

**Issue by aswild** [gyscos/zstd-rs#89]
I'm trying to use multi-threaded compression from the high-level API (specifically zstd::stream::read::Encoder's multithread() method), but the `zstdmt` feature of zstd-safe and zstd-sys isn't "exported" up to the high-level zstd crate.

**Request:** could you add the zstdmt feature to the zstd crate that turns on zstd-safe/zstdmt (and thus zstd-sys/zstdmt)?

To work around that, I added this to my Cargo.toml's dependencies, which is clunky but ought to work anyway.
```toml
zstd = "0.5.2"
zstd-safe = { version = "2.0.4", features = ["zstdmt"] }
```

This is where things get weird.

Building with `cargo build -vv` I can see that the zstd C code is getting compiled with `-pthread`, but the `-DZSTD_MULTITHREAD=` option from https://github.com/gyscos/zstd-rs/pull/84 is missing, and I can't figure out why.

According to Cargo.lock, I'm building version `2.0.4+zstd.1.4.5` of zstd-sys, which was added in commit 0be78635723e9fe2dce6556455309ab240956925 of this repo and contains commit 3b83579b3a8b4e1d6e841fa5eb6252d4c81af040 from #84. That seems good, but the build.rs fix isn't actually in the code that cargo is downloading and building from crates.io.

I looked in cargo's registry cache and `~/.cargo/registry/src/github.com-1ecc6299db9ec823/zstd-sys-1.4.16+zstd.1.4.5/.cargo_vcs_info.json` says that the git revision is ad9ee49769fce9cd540330873da11624db826389, a commit that doesn't actually exist in this repo.

I'm really confused, how are these versions out of sync?

If I ignore crates.io and point directly to the git repo for all 3 crates, or clone zstd-rs locally and use a path in Cargo.toml, it works.
```toml
zstd = { git="https://github.com/gyscos/zstd-rs", rev="0be7863" }
zstd-safe = { git="https://github.com/gyscos/zstd-rs", rev="0be7863", features=["zstdmt"] }
zstd-sys = { git="https://github.com/gyscos/zstd-rs", rev="0be7863", features=["zstdmt"] }
```
